/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'mwypych' at '10.11.16 01:12' with Gradle 3.0
 *
 * @author mwypych, @date 10.11.16 01:12
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
