/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'mwypych' at '10.11.16 01:12' with Gradle 3.0
 *
 * @author mwypych, @date 10.11.16 01:12
 */

import org.scalatest._

class LibrarySpec extends FlatSpec with Matchers {

  "This test" should "fail" in {
    fail()
  }
}
