/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'mwypych' at '10.11.16 01:12' with Gradle 3.0
 *
 * @author mwypych, @date 10.11.16 01:12
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
